# Conda environment file
# Add your package dependencies in pyproject.toml

name: snowpark_default
channels:
  - snowflake
dependencies:
  - python=3.10
  - pip
  - setuptools>=64
  - pip:
      - "-e ."
